name: Lint Python code

on:
  push:
    paths:
    - ".github/workflows/pylinter.yml"
    - "src/**"
  pull_request:
    paths:
    - ".github/workflows/pylinter.yml"
    - "src/**"

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
    - name: Checkout source repo
      uses: actions/checkout@v2

    - name: Linting
      uses: alexanderdamiani/pylinter@v1.1.0
      with:
        python-root: './src'
        skip-mypy: true
        flake8-flags: --ignore=E121,E123,E126,E226,E24,E501,E704
    
     - name: Commit isort changes
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A && git diff-index --cached --quiet HEAD || git commit -m '🎨 Run isort'

    - name: Push isort changes
      if: ${{ github.event_name != 'pull_request' }}
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}